version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=${VITE_API_URL}
        - VITE_API_URL_REMOTE=${VITE_API_URL_REMOTE}
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_API_URL_REMOTE=${VITE_API_URL_REMOTE}
    ports:
      - "5137:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "7315:7315"
    volumes:
      - uploads:/app/uploads
    environment:
      - FLASK_ENV=production
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
    name: jobpal_postgres_data
  uploads:
    name: jobpal_uploads
